### ISSUE TITLE
An open3d error occurred, when I tried to visualize the results in the docker container, how can I fix it ?

### ISSUE THREAD

**Issue by jiangxuan2023** [tusen-ai/SST#101]
[Open3D WARNING] GLFW Error: GLX: No GLXFBConfigs returned
[Open3D WARNING] GLFW Error: GLX: Failed to find a suitable GLXFBConfig
[Open3D WARNING] Failed to create window

Traceback (most recent call last):
  File "tools/test.py", line 224, in <module>
    main()
  File "tools/test.py", line 194, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/data/jiangx/code/SST/mmdet3d/apis/test.py", line 52, in single_gpu_test
    model.module.show_results(data, result, out_dir)
  File "/data/jiangx/code/SST/mmdet3d/models/detectors/base.py", line 107, in show_results
    show_result(points, None, pred_bboxes, out_dir, file_name)
  File "/data/jiangx/code/SST/mmdet3d/core/visualizer/show_result.py", line 99, in show_result
    vis = Visualizer(points)
  File "/data/jiangx/code/SST/mmdet3d/core/visualizer/open3d_vis.py", line 362, in __init__
    self.o3d_visualizer = o3d.visualization.Visualizer()
  File "/data/jiangx/code/SST/mmdet3d/core/visualizer/open3d_vis.py", line 34, in _draw_points
    vis.get_render_option().point_size = points_size  # set points size
AttributeError: 'NoneType' object has no attribute 'point_size'

**Comment by Abyssaledge** [comment]
Sorry, I have not tried the default visualization function. It may not be completely compatible with our code.
