### ISSUE TITLE
run dist_test.sh error with fsdv2

### ISSUE THREAD

**Issue by atlantins** [tusen-ai/SST#146]
when i run(i copy fsdv2_waymo_2x_bb01_ms.py to tools/dist_test.sh configs/fsdv2/, get from https://github.com/tusen-ai/SST/blob/main/docs/fsdv2_instructions.md google drive) 
bash tools/dist_test.sh configs/fsdv2/fsdv2_waymo_2x_bb01_ms.py ctrl_bins/detection_model/fsdv2_waymo_2x_workdir/fsdv2_waymo_2x_workdir/epoch_24.pth 8 --options "pklfile_prefix=./inference/test/test_results"  --eval waymo

Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
<mmdet3d.datasets.waymo_dataset.WaymoDataset object at 0x7f34b0824b80>
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
<mmdet3d.datasets.waymo_dataset.WaymoDataset object at 0x7f567603fbb0>
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
<mmdet3d.datasets.waymo_dataset.WaymoDataset object at 0x7fd9d3aacbe0>
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
<mmdet3d.datasets.waymo_dataset.WaymoDataset object at 0x7f6669d43be0>
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
<mmdet3d.datasets.waymo_dataset.WaymoDataset object at 0x7fb465993a30>
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
<mmdet3d.datasets.waymo_dataset.WaymoDataset object at 0x7f1a06902be0>
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
<mmdet3d.datasets.waymo_dataset.WaymoDataset object at 0x7f7fabb73a30>
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/xhj/SST2/mmdet3d/models/detectors/two_stage_fsd_v2.py", line 28, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage_fsd_v2.py", line 54, in __init__
    super().__init__(
  File "/home/xhj/SST2/mmdet3d/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmdet/models/builder.py", line 19, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'FSDV2SparseUNet is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 234, in <module>
    main()
  File "tools/test.py", line 183, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 83, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/home/xhj/SST2/mmdet3d/models/builder.py", line 56, in build_detector
    return DETECTORS.build(
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FSDV2: 'FSDV2SparseUNet is not in the models registry'"
Killing subprocess 49614
Killing subprocess 49618
Killing subprocess 49620
Killing subprocess 49621
Killing subprocess 49622
Killing subprocess 49626
Killing subprocess 49630
Killing subprocess 49632
Traceback (most recent call last):
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/xhj/miniconda3/envs/ctrl_official/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/xhj/miniconda3/envs/ctrl_official/bin/python', '-u', 'tools/test.py', '--local_rank=7', 'configs/fsdv2/fsdv2_waymo_2x_bb01_ms.py', 'ctrl_bins/detection_model/fsdv2_waymo_2x_workdir/fsdv2_waymo_2x_workdir/epoch_24.pth', '--launcher', 'pytorch', '--options', 'pklfile_prefix=./inference/test/test_results', '--eval', 'waymo']' returned non-zero exit status 1.

**Comment by Abyssaledge** [comment]
Please use the config in this repo, instead of the one in provided resources. We renamed some modules.

**Comment by atlantins** [comment]
thanks!
