### ISSUE TITLE
'ConfigDict' object has no attribute 'device'

### ISSUE THREAD

**Issue by SH-Tan** [tusen-ai/SST#76]
Hello, I tried to change the config file to kitti dataset, and get the below error message. I did not find any device cfg info in other config files, should I add the device info in config file?

> Traceback (most recent call last):
  File "tools/train.py", line 230, in <module>
    main()
  File "tools/train.py", line 220, in main
    train_model(
  File "/home/tan/SST/mmdet3d/apis/train.py", line 27, in train_model
    train_detector(
  File "/home/tan/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmdet/apis/train.py", line 163, in train_detector
    model = build_dp(model, cfg.device, device_ids=cfg.gpu_ids)
  File "/home/tan/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device'

**Comment by SH-Tan** [comment]
solved by added "device='cuda'" in config file
